<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [13]:
import h5py
import numpy as np

from keras.utils import to_categorical
from sklearn import preprocessing

In [4]:
hf = h5py.File('../dataset/h5py/train_hf128_7', 'r')
list(hf.keys())

['ct_image_0',
 'ct_image_1',
 'ct_image_10',
 'ct_image_11',
 'ct_image_12',
 'ct_image_13',
 'ct_image_14',
 'ct_image_15',
 'ct_image_16',
 'ct_image_17',
 'ct_image_18',
 'ct_image_19',
 'ct_image_2',
 'ct_image_3',
 'ct_image_4',
 'ct_image_5',
 'ct_image_6',
 'ct_image_7',
 'ct_image_8',
 'ct_image_9',
 'ct_image_mask_0',
 'ct_image_mask_1',
 'ct_image_mask_10',
 'ct_image_mask_11',
 'ct_image_mask_12',
 'ct_image_mask_13',
 'ct_image_mask_14',
 'ct_image_mask_15',
 'ct_image_mask_16',
 'ct_image_mask_17',
 'ct_image_mask_18',
 'ct_image_mask_19',
 'ct_image_mask_2',
 'ct_image_mask_3',
 'ct_image_mask_4',
 'ct_image_mask_5',
 'ct_image_mask_6',
 'ct_image_mask_7',
 'ct_image_mask_8',
 'ct_image_mask_9',
 'ct_label_0',
 'ct_label_1',
 'ct_label_10',
 'ct_label_11',
 'ct_label_12',
 'ct_label_13',
 'ct_label_14',
 'ct_label_15',
 'ct_label_16',
 'ct_label_17',
 'ct_label_18',
 'ct_label_19',
 'ct_label_2',
 'ct_label_3',
 'ct_label_4',
 'ct_label_5',
 'ct_label_6',
 'ct_label_7',


In [23]:
hf['ct_label_0'].shape

(128, 128, 128, 8)

In [30]:
np.unique(np.argmax(np.array(hf['ct_label_0']), axis=-1))

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [21]:
a = np.array([200,100,300,400])
label_encoder = preprocessing.LabelEncoder()
a = label_encoder.fit_transform(a)
print(a)

[1 0 2 3]


In [22]:
a = np.array([200,300,100,400])

label_encoder = preprocessing.LabelEncoder()
a = label_encoder.fit_transform(a)

print(a)

[1 2 0 3]
