<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import numpy as np

In [109]:
batch_shape, dim1, dim2, dim3 = 1,8,9,10

In [177]:
xx_ones = np.ones(np.stack([batch_shape, dim2]), dtype='int32')
print(xx_ones.shape)
xx_range = np.tile(np.expand_dims(np.arange(0, dim3), axis=1),
                  np.stack([batch_shape, 1]))
print(xx_range.shape)
xx_channels = np.dot(xx_range, xx_ones)
print(xx_channels.shape)
xx_channels = np.expand_dims(xx_channels, axis=-1)
print(xx_channels.shape)
xx_channels = np.transpose(xx_channels, [1, 0, 2])
print(xx_channels.shape)
xx_channels = np.expand_dims(xx_channels, axis=0)
print(xx_channels.shape)
xx_channels = np.tile(xx_channels,[dim1, 1, 1, 1]).astype(np.float32)
print(xx_channels.shape)
np.squeeze(xx_channels)

(1, 9)
(10, 1)
(10, 9)
(10, 9, 1)
(9, 10, 1)
(1, 9, 10, 1)
(8, 9, 10, 1)


array([[[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]],

       [[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]],

       [[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9

In [164]:
yy_ones = np.ones(np.stack([dim3, batch_shape]), dtype='int32')
print(yy_ones.shape)
yy_range = np.tile(np.expand_dims(np.arange(0, dim2), axis=0),
                  np.stack([batch_shape, 1]))
print(yy_range.shape)
yy_channels = np.dot(yy_ones, yy_range)
print(yy_channels.shape)
yy_channels = np.expand_dims(yy_channels, axis=-1)
print(yy_channels.shape)
yy_channels = np.transpose(yy_channels, [1, 0, 2])
print(yy_channels.shape)
yy_channels = np.expand_dims(yy_channels, axis=0)
print(yy_channels.shape)
yy_channels = np.tile(yy_channels,[dim1, 1, 1, 1])
print(yy_channels.shape)
np.squeeze(yy_channels)

(10, 1)
(1, 9)
(10, 9)
(10, 9, 1)
(9, 10, 1)
(1, 9, 10, 1)
(8, 9, 10, 1)


array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 

In [166]:
zz_range = np.tile(np.expand_dims(np.arange(0, dim1), axis=1), np.stack([batch_shape, 1]))
print(zz_range.shape)
zz_range = np.expand_dims(zz_range, axis=-1)
print(zz_range.shape)
zz_channels = np.tile(zz_range, [1, dim2, dim3])
print(zz_channels.shape)
zz_channels = np.expand_dims(zz_channels, axis=-1)
print(zz_channels.shape)
np.squeeze(zz_channels)

(8, 1)
(8, 1, 1)
(8, 9, 10)
(8, 9, 10, 1)


array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 

In [173]:
def CoordinateChannel3D(image):
    assert len(image.shape) == 4 # weight, height, depth, channel
    batch_shape = 1
    input_shape = image.shape
    input_shape = [input_shape[i] for i in range(4)]
    dim1, dim2, dim3, channels = input_shape

    xx_ones = np.ones(np.stack([batch_shape, dim2]), dtype='int32')
    
    xx_range = np.tile(np.expand_dims(np.arange(0, dim3), axis=1), np.stack([batch_shape, 1]))
    
    xx_channels = np.dot(xx_range, xx_ones)
    xx_channels = np.expand_dims(xx_channels, axis=-1)
    xx_channels = np.transpose(xx_channels, [1, 0, 2])
    xx_channels = np.expand_dims(xx_channels, axis=0)
    xx_channels = np.tile(xx_channels,[dim1, 1, 1, 1])

    yy_ones = np.ones(np.stack([dim3, batch_shape]), dtype='int32')
    
    yy_range = np.tile(np.expand_dims(np.arange(0, dim2), axis=0), np.stack([batch_shape, 1]))
    
    yy_channels = np.dot(yy_ones, yy_range)
    yy_channels = np.expand_dims(yy_channels, axis=-1)
    yy_channels = np.transpose(yy_channels, [1, 0, 2])
    yy_channels = np.expand_dims(yy_channels, axis=0)
    yy_channels = np.tile(yy_channels,[dim1, 1, 1, 1])

    zz_range = np.tile(np.expand_dims(np.arange(0, dim1), axis=1), np.stack([batch_shape, 1]))
    zz_range = np.expand_dims(zz_range, axis=-1)
    
    zz_channels = np.tile(zz_range, [1, dim2, dim3])
    zz_channels = np.expand_dims(zz_channels, axis=-1)

    xx_channels = xx_channels.astype(np.float32)
    xx_channels = xx_channels /(dim2 - 1)
    xx_channels = xx_channels * 2 - 1.

    yy_channels = yy_channels.astype(np.float32)
    yy_channels = yy_channels / (dim3 - 1)
    yy_channels = yy_channels * 2 - 1.

    zz_channels = zz_channels.astype(np.float32)
    zz_channels = zz_channels / (dim1 - 1)
    zz_channels = zz_channels * 2 - 1.

    outputs = np.concatenate([image, zz_channels, xx_channels, yy_channels],
                            axis=-1)

    return outputs

In [174]:
image = np.random.random((26,27,28,1))
image.shape

(26, 27, 28, 1)

In [175]:
output = CoordinateChannel3D(image)

(26, 27, 28, 1)
(26, 27, 28, 1)
(26, 27, 28, 1)
(26, 27, 28, 1)


In [176]:
output

array([[[[ 0.82262155, -1.        , -1.        , -1.        ],
         [ 0.80275411, -1.        , -0.92307693, -1.        ],
         [ 0.98885342, -1.        , -0.84615386, -1.        ],
         ...,
         [ 0.84243832, -1.        ,  0.92307687, -1.        ],
         [ 0.62701826, -1.        ,  1.        , -1.        ],
         [ 0.57517155, -1.        ,  1.07692313, -1.        ]],

        [[ 0.04425842, -1.        , -1.        , -0.92592591],
         [ 0.23384563, -1.        , -0.92307693, -0.92592591],
         [ 0.75859073, -1.        , -0.84615386, -0.92592591],
         ...,
         [ 0.24121733, -1.        ,  0.92307687, -0.92592591],
         [ 0.93548743, -1.        ,  1.        , -0.92592591],
         [ 0.42332657, -1.        ,  1.07692313, -0.92592591]],

        [[ 0.97180404, -1.        , -1.        , -0.85185182],
         [ 0.93336267, -1.        , -0.92307693, -0.85185182],
         [ 0.85545755, -1.        , -0.84615386, -0.85185182],
         ...,
         

In [134]:
import tensorflow as tf

C:\Users\wogur\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [135]:
sess = tf.Session()

In [137]:
xx_ones = tf.ones([batch_shape, dim3], dtype=tf.int32)
xx_ones = tf.expand_dims(xx_ones,-1)
sess.run(xx_ones)

array([[[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1]]])

In [142]:
xx_range = tf.tile(tf.expand_dims(tf.range(dim2), 0), [batch_shape, 1])
xx_range = tf.expand_dims(xx_range, 1)
sess.run(xx_range)

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8]]])

In [144]:
xx_channel = tf.matmul(xx_ones, xx_range)
sess.run(xx_channel)

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]]])

In [145]:
xx_channel = tf.expand_dims(xx_channel, -1)
sess.run(xx_channel)

array([[[[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]],

        [[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]],

        [[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]],

        [[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]],

        [[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]],

        [[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]],

        [[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]],

        [[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
      

In [153]:
yy_ones = tf.ones([batch_shape, dim2],dtype=tf.int32)
yy_ones = tf.expand_dims(yy_ones, 1)
yy_range = tf.tile(tf.expand_dims(tf.range(dim3), 0),[batch_shape, 1])
yy_range = tf.expand_dims(yy_range, -1)
yy_channel = tf.matmul(yy_range, yy_ones)
yy_channel = tf.expand_dims(yy_channel, -1)
sess.run(yy_channel)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8, 8, 8, 8, 8],
        [9, 9, 9, 9, 9, 9, 9, 9, 9]]])